(ns ninthodds.mu
  (:require [reagent.core :as reagent]
            [cljsjs.material-ui]))

(def AppBar (reagent/adapt-react-class (aget js/MaterialUI "AppBar")))
(def AutoComplete (reagent/adapt-react-class (aget js/MaterialUI "AutoComplete")))
(def Avatar (reagent/adapt-react-class (aget js/MaterialUI "Avatar")))
(def Badge (reagent/adapt-react-class (aget js/MaterialUI "Badge")))
(def BottomNavigation (reagent/adapt-react-class (aget js/MaterialUI "BottomNavigation")))
(def BottomNavigationItem (reagent/adapt-react-class (aget js/MaterialUI "BottomNavigationItem")))
(def Card (reagent/adapt-react-class (aget js/MaterialUI "Card")))
(def CardActions (reagent/adapt-react-class (aget js/MaterialUI "CardActions")))
(def CardHeader (reagent/adapt-react-class (aget js/MaterialUI "CardHeader")))
(def CardMedia (reagent/adapt-react-class (aget js/MaterialUI "CardMedia")))
(def CardText (reagent/adapt-react-class (aget js/MaterialUI "CardText")))
(def CardTitle (reagent/adapt-react-class (aget js/MaterialUI "CardTitle")))
(def Checkbox (reagent/adapt-react-class (aget js/MaterialUI "Checkbox")))
(def Chip (reagent/adapt-react-class (aget js/MaterialUI "Chip")))
(def CircularProgress (reagent/adapt-react-class (aget js/MaterialUI "CircularProgress")))
(def DatePicker (reagent/adapt-react-class (aget js/MaterialUI "DatePicker")))
(def Dialog (reagent/adapt-react-class (aget js/MaterialUI "Dialog")))
(def Divider (reagent/adapt-react-class (aget js/MaterialUI "Divider")))
(def Drawer (reagent/adapt-react-class (aget js/MaterialUI "Drawer")))
(def DropDownMenu (reagent/adapt-react-class (aget js/MaterialUI "DropDownMenu")))
(def FlatButton (reagent/adapt-react-class (aget js/MaterialUI "FlatButton")))
(def FloatingActionButton (reagent/adapt-react-class (aget js/MaterialUI "FloatingActionButton")))
(def FontIcon (reagent/adapt-react-class (aget js/MaterialUI "FontIcon")))
(def GridList (reagent/adapt-react-class (aget js/MaterialUI "GridList")))
(def GridTile (reagent/adapt-react-class (aget js/MaterialUI "GridTile")))
(def IconButton (reagent/adapt-react-class (aget js/MaterialUI "IconButton")))
(def IconMenu (reagent/adapt-react-class (aget js/MaterialUI "IconMenu")))
(def LinearProgress (reagent/adapt-react-class (aget js/MaterialUI "LinearProgress")))
(def List (reagent/adapt-react-class (aget js/MaterialUI "List")))
(def ListItem (reagent/adapt-react-class (aget js/MaterialUI "ListItem")))
(def Menu (reagent/adapt-react-class (aget js/MaterialUI "Menu")))
(def MenuItem (reagent/adapt-react-class (aget js/MaterialUI "MenuItem")))
(def Paper (reagent/adapt-react-class (aget js/MaterialUI "Paper")))
(def Popover (reagent/adapt-react-class (aget js/MaterialUI "Popover")))
(def RadioButton (reagent/adapt-react-class (aget js/MaterialUI "RadioButton")))
(def RadioButtonGroup (reagent/adapt-react-class (aget js/MaterialUI "RadioButtonGroup")))
(def RaisedButton (reagent/adapt-react-class (aget js/MaterialUI "RaisedButton")))
(def RefreshIndicator (reagent/adapt-react-class (aget js/MaterialUI "RefreshIndicator")))
(def SelectField (reagent/adapt-react-class (aget js/MaterialUI "SelectField")))
(def Slider (reagent/adapt-react-class (aget js/MaterialUI "Slider")))
(def Snackbar (reagent/adapt-react-class (aget js/MaterialUI "Snackbar")))
(def Step (reagent/adapt-react-class (aget js/MaterialUI "Step")))
(def StepButton (reagent/adapt-react-class (aget js/MaterialUI "StepButton")))
(def StepContent (reagent/adapt-react-class (aget js/MaterialUI "StepContent")))
(def StepLabel (reagent/adapt-react-class (aget js/MaterialUI "StepLabel")))
(def Stepper (reagent/adapt-react-class (aget js/MaterialUI "Stepper")))
(def Subheader (reagent/adapt-react-class (aget js/MaterialUI "Subheader")))
(def SvgIcon (reagent/adapt-react-class (aget js/MaterialUI "SvgIcon")))
(def Tab (reagent/adapt-react-class (aget js/MaterialUI "Tab")))
(def Tabs (reagent/adapt-react-class (aget js/MaterialUI "Tabs")))
(def Table (reagent/adapt-react-class (aget js/MaterialUI "Table")))
(def TableBody (reagent/adapt-react-class (aget js/MaterialUI "TableBody")))
(def TableFooter (reagent/adapt-react-class (aget js/MaterialUI "TableFooter")))
(def TableHeader (reagent/adapt-react-class (aget js/MaterialUI "TableHeader")))
(def TableHeaderColumn (reagent/adapt-react-class (aget js/MaterialUI "TableHeaderColumn")))
(def TableRow (reagent/adapt-react-class (aget js/MaterialUI "TableRow")))
(def TableRowColumn (reagent/adapt-react-class (aget js/MaterialUI "TableRowColumn")))
(def TimePicker (reagent/adapt-react-class (aget js/MaterialUI "TimePicker")))
(def TextField (reagent/adapt-react-class (aget js/MaterialUI "TextField")))
(def Toggle (reagent/adapt-react-class (aget js/MaterialUI "Toggle")))
(def Toolbar (reagent/adapt-react-class (aget js/MaterialUI "Toolbar")))
(def ToolbarGroup (reagent/adapt-react-class (aget js/MaterialUI "ToolbarGroup")))
(def ToolbarSeparator (reagent/adapt-react-class (aget js/MaterialUI "ToolbarSeparator")))
(def ToolbarTitle (reagent/adapt-react-class (aget js/MaterialUI "ToolbarTitle")))

(def colors (aget js/MaterialUIStyles "colors"))

(def lightBaseTheme (aget js/MaterialUIStyles "lightBaseTheme"))

(def darkBaseTheme (aget js/MaterialUIStyles "darkBaseTheme"))

(def getMuiTheme (aget js/MaterialUIStyles "getMuiTheme"))

(def MuiThemeProvider (-> js/MaterialUIStyles
                          (aget "MuiThemeProvider")
                          reagent/adapt-react-class))
